src/2012/C#/YakinikuClub/version0.0.1/YakinikuClubV2/Models/Account/ChangePasswordModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using YakinikuClubV2.Common;

namespace YakinikuClubV2.Models.Account
{
	public class ChangePasswordModel
	{
		[Required]
		[DataType(DataType.Password)]
		[Display(Name = "現在のパスワード")]
		public string OldPassword { get; set; }

		[Required]
		[StringLength(Constants.Model.PasswordMaxLength, MinimumLength = Constants.Model.PasswordMinLength, ErrorMessage = "{0}は{2}～{1}文字で入力してください。")]
		[DataType(DataType.Password)]
		[Display(Name = "新しいパスワード")]
		public string NewPassword { get; set; }

		[DataType(DataType.Password)]
		[Display(Name = "確認用パスワード")]
		[Compare("NewPassword", ErrorMessage = "入力した新しいパスワードと異なります。")]
		public string ConfirmPassword { get; set; }
	}
}

src/2012/C#/YakinikuClub/version0.0.1/YakinikuClubV2/Models/Account/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace YakinikuClubV2.Models.Account
{
	public class LoginModel
	{
		[Required]
		[Display(Name = "ユーザ名")]
		public string UserName { get; set; }

		[Required]
		[DataType(DataType.Password)]
		[Display(Name = "パスワード")]
		public string Password { get; set; }
	}
}

src/2012/C#/YakinikuClub/version0.0.1/YakinikuClubV2/Models/Account/RegisterModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using YakinikuClubV2.Common;
using YakinikuClubV2.Validation;

namespace YakinikuClubV2.Models.Account
{
	public class RegisterModel
	{
		[Required]
		[Display(Name = "ユーザ名")]
		public string UserName { get; set; }

		[Required]
		[DataType(DataType.EmailAddress)]
		[Display(Name = "メールアドレス")]
		public string Email { get; set; }

		[Required]
		[StringLength(Constants.Model.PasswordMaxLength, MinimumLength = Constants.Model.PasswordMinLength, ErrorMessage = "{0}は{2}～{1}文字で入力してください。")]
		[DataType(DataType.Password)]
		[Display(Name = "パスワード")]
		public string Password { get; set; }

		[DataType(DataType.Password)]
		[Display(Name = "確認用パスワード")]
		[Compare("Password", ErrorMessage = "入力したパスワードと異なります。")]
		public string ConfirmPassword { get; set; }

		[Required]
		[DataType(DataType.Password)]
		[Display(Name = "合言葉")]
		[WatchwordValidation(ErrorMessage = "合言葉が違います。")]
		public string Watchword { get; set; }
	}
}

src/2012/C#/YakinikuClub/version0.0.1/YakinikuClubV2/Models/ModelBase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace YakinikuClubV2.Models
{
	abstract class ModelBase
	{
	}
}

src/2012/C#/YakinikuClub/version0.0.1/YakinikuClubV2/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using YakinikuClubV2.Models.Account;

namespace YakinikuClubV2.Controllers
{
	[Authorize]
	public class AccountController : Controller
	{
		// GET: /Account/Login
		[AllowAnonymous]
		public ActionResult Login()
		{
			return View();
		}

		// POST: /Account/Login
		[AllowAnonymous]
		[HttpPost]
		public ActionResult Login(LoginModel model, string returnUrl)
		{
			if (ModelState.IsValid)
			{
				if (Membership.ValidateUser(model.UserName, model.Password))
				{
					FormsAuthentication.SetAuthCookie(model.UserName, true);
					if (Url.IsLocalUrl(returnUrl))
					{
						return Redirect(returnUrl);
					}
					else
					{
						return RedirectToAction("Index", "Home");
					}
				}
				else
				{
					ModelState.AddModelError("", "The user name or password provided is incorrect.");
				}
			}

			// If we got this far, something failed, redisplay form
			return View(model);
		}

		// GET: /Account/Logout
		public ActionResult Logout()
		{
			FormsAuthentication.SignOut();
			return RedirectToAction("Index", "Home");
		}

		// GET: /Account/Register
		[AllowAnonymous]
		public ActionResult Register()
		{
			return View();
		}

		// POST: /Account/Register
		[AllowAnonymous]
		[HttpPost]
		public ActionResult Register(RegisterModel model)
		{
			if (ModelState.IsValid)
			{
				// Attempt to register the user
				MembershipCreateStatus createStatus;
				Membership.CreateUser(model.UserName, model.Password, model.Email, passwordQuestion: null, passwordAnswer: null, isApproved: true, providerUserKey: null, status: out createStatus);

				if (createStatus == MembershipCreateStatus.Success)
				{
					FormsAuthentication.SetAuthCookie(model.UserName, createPersistentCookie: false);
					return RedirectToAction("Index", "Home");
				}
				else
				{
					ModelState.AddModelError("", ErrorCodeToString(createStatus));
				}
			}

			// If we got this far, something failed, redisplay form
			return View(model);
		}

		// GET: /Account/ChangePassword
		public ActionResult ChangePassword()
		{
			return View();
		}

		// POST: /Account/ChangePassword
		[HttpPost]
		public ActionResult ChangePassword(ChangePasswordModel model)
		{
			if (ModelState.IsValid)
			{
				// ChangePassword will throw an exception rather
				// than return false in certain failure scenarios.
				bool changePasswordSucceeded;
				try
				{
					MembershipUser currentUser = Membership.GetUser(User.Identity.Name, userIsOnline: true);
					changePasswordSucceeded = currentUser.ChangePassword(model.OldPassword, model.NewPassword);
				}
				catch (Exception)
				{
					changePasswordSucceeded = false;
				}

				if (changePasswordSucceeded)
				{
					return RedirectToAction("ChangePasswordSuccess");
				}
				else
				{
					ModelState.AddModelError("", "The current password is incorrect or the new password is invalid.");
				}
			}

			// If we got this far, something failed, redisplay form
			return View(model);
		}

		// GET: /Account/ChangePasswordSuccess
		public ActionResult ChangePasswordSuccess()
		{
			return View();
		}

		private IEnumerable<string> GetErrorsFromModelState()
		{
			return ModelState.SelectMany(x => x.Value.Errors.Select(error => error.ErrorMessage));
		}

		#region Status Codes
		private static string ErrorCodeToString(MembershipCreateStatus createStatus)
		{
			// See http://go.microsoft.com/fwlink/?LinkID=177550 for
			// a full list of status codes.
			switch (createStatus)
			{
			case MembershipCreateStatus.DuplicateUserName:
				return "User name already exists. Please enter a different user name.";

			case MembershipCreateStatus.DuplicateEmail:
				return "A user name for that e-mail address already exists. Please enter a different e-mail address.";

			case MembershipCreateStatus.InvalidPassword:
				return "The password provided is invalid. Please enter a valid password value.";

			case MembershipCreateStatus.InvalidEmail:
				return "The e-mail address provided is invalid. Please check the value and try again.";

			case MembershipCreateStatus.InvalidAnswer:
				return "The password retrieval answer provided is invalid. Please check the value and try again.";

			case MembershipCreateStatus.InvalidQuestion:
				return "The password retrieval question provided is invalid. Please check the value and try again.";

			case MembershipCreateStatus.InvalidUserName:
				return "The user name provided is invalid. Please check the value and try again.";

			case MembershipCreateStatus.ProviderError:
				return "The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator.";

			case MembershipCreateStatus.UserRejected:
				return "The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator.";

			default:
				return "An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator.";
			}
		}
		#endregion
	}
}

src/2012/C#/YakinikuClub/version0.0.1/YakinikuClubV2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace YakinikuClubV2.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			ViewBag.Message = "ようこそ！";
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "焼肉部について";
			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "焼肉部情報";
			return View();
		}
	}
}

src/2012/C#/YakinikuClub/version0.0.1/YakinikuClubV2/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace YakinikuClubV2.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

src/2012/C#/YakinikuClub/version0.0.1/YakinikuClubV2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>

<article>
    <p>a</p>
    <p>b</p>
    <p>c</p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>aaa</p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

src/2012/C#/YakinikuClub/version0.0.1/YakinikuClubV2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>

<section class="contact">
    <header>
        <h3>メール:</h3>
    </header>
    <p>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
</section>

src/2012/C#/YakinikuClub/version0.0.1/YakinikuClubV2/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" href="@Url.Content("~/Content/jquery.mobile-1.1.0.min.css")" />
        <link rel="stylesheet" href="@Url.Content("~/Content/Site.Mobile.css")" />
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.7.2.min.js")"></script>
        <script type="text/javascript">
            $(document).bind("mobileinit", function() {
                // As of Beta 2, jQuery Mobile's Ajax navigation does not work in all cases (e.g.,
                // when navigating from a mobile to a non-mobile page), hence disabling it.
                $.mobile.ajaxEnabled = false;
            });
        </script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.mobile-1.1.0.min.js")"></script>
    </head> 
<body> 

    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
            <h1>@ViewBag.Title</h1>
        </div>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

    </div>

</body>
</html>

src/2012/C#/YakinikuClub/version0.0.1/YakinikuClubV2/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}