src/2012/C#/YakinikuClub/version0.0.1/YakinikuClub/Controllers/ClubActivityController.cs
using System.Web.Mvc;
using YakinikuClub.Binders;
using YakinikuClub.Helpers;
using YakinikuClub.Models.Db;
using YakinikuClub.Models.Repository;
using YakinikuClub.ViewModels;
using YakinikuClub.ViewModels.ClubActivity;
using YakinikuClub.ViewModels.History;

namespace YakinikuClub.Controllers
{
	public class ClubActivityController : Controller
	{
		[Authorize]
		public ActionResult Plan()
		{
			var model = this.GetMemberInfo();
			ViewBag.IsAdministrator = model.IsAdministrator;
			return View(new PlanViewModel());
		}

		[Authorize]
		public ActionResult History()
		{
			var model = this.GetMemberInfo();
			ViewBag.IsAdministrator = model.IsAdministrator;
			return View(new HistoryListViewModel());
		}

		[HttpPost]
		public ActionResult Register(
			[ModelBinder(typeof(ManagementViewModelBinder))] ClubActivityViewModel data)
		{
			if (ModelState.IsValid)
			{
				using (var ctx = new YakinikuClubDbContext())
				{
					var repos = new ClubActivityRepository(ctx);
					repos.AddClubActivity(data);
					ctx.SaveChanges();
				}
				return RedirectToAction("Index", "Home");
			}
			return RedirectToAction("Index", "Management");
		}

	}
}

src/2012/C#/YakinikuClub/version0.0.1/YakinikuClub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="keywords" content="yakiniku,焼肉部" />
  <meta name="description" content="焼肉部（非公式）サイトです。" />
  <title>@ViewBag.Title</title>
  <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
  <link href="@Url.Content("~/Content/my.css")" rel="stylesheet" type="text/css" />
  <link href="@Url.Content("~/Content/tablesorter/blue.css")" rel="stylesheet" type="text/css" />
  <link href="@Url.Content("~/Content/jQuery/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
  <script src="@Url.Content("~/Scripts/lib/jQuery/jquery-1.7.2.min.js")" type="text/javascript"></script>
  <script src="@Url.Content("~/Scripts/lib/jQuery/jquery-ui-1.8.18.min.js")" type="text/javascript"></script>
  <script src="@Url.Content("~/Scripts/lib/jQuery/jquery.tablesorter.min.js")" type="text/javascript"></script>
  <script src="@Url.Content("~/Scripts/lib/Modernizr/modernizr-2.5.3.js")" type="text/javascript"></script>
  <script type="text/javascript" src="http://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load("maps", "3", { "other_params": "sensor=false" });
  </script>
</head>
<body>
  <div class="page">
    <header>
      <div id="title">
        <h1>@Html.ActionLink("焼肉部", "Index", "Home")</h1>
      </div>
      <div id="logindisplay">
        @Html.Partial("_LogOnPartial")
      </div>
      <nav>
        <ul id="menu">
          <li>@Html.ActionLink("Home", "Index", "Home")</li>
        @if (Request.IsAuthenticated)
        {
          <li>@Html.ActionLink("Member", "Index", "Member")</li>
          <li>@Html.ActionLink("Plan", "Plan", "ClubActivity")</li>
          <li>@Html.ActionLink("History", "History", "ClubActivity")</li>
          if (ViewBag.IsAdministrator)
          {
            <li>@Html.ActionLink("Management", "Index", "Management")</li>
          }
        }
          <li>@Html.ActionLink("About", "About", "Home")</li>
        </ul>
      </nav>
    </header>
    <section id="main">
      <!-- index part start -->
      @RenderBody()
      <!-- index part end -->
    </section>
    <footer>
    </footer>
  </div>
</body>
</html>

src/2012/C#/YakinikuClub/version0.0.1/YakinikuClub/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated){
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("ログオフ", "LogOff", "Account") ]</text>
}
else{
    @:[ @Html.ActionLink("ログオン", "LogOn", "Account") ]
}